package org.lpnu.chef_app.controller;

import javafx.application.Platform;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.control.*;
import javafx.stage.Stage;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.lpnu.chef_app.model.*;
import org.lpnu.chef_app.model.enums.ProcessingState;
import org.lpnu.chef_app.repository.SaladRepository;
import org.mockito.Mockito;
import org.testfx.framework.junit5.ApplicationTest;
import org.testfx.util.WaitForAsyncUtils;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.util.List;
import java.util.Locale;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

public class RecipeBookControllerTest extends ApplicationTest {

    private RecipeBookController controller;
    private SaladRepository mockSaladRepo;
    private MainController mockMainController;
    private Salad testSalad;

    @Override
    public void start(Stage stage) throws Exception {
        Locale.setDefault(Locale.US); // Double format (0.0 instead of 0,0)

        String h2Url = System.getProperty("test.db.url");
        if (h2Url == null) {
            h2Url = "jdbc:h2:mem:salad_db;DB_CLOSE_DELAY=-1;MODE=PostgreSQL";
            System.setProperty("test.db.url", h2Url);
        }

        try (Connection conn = DriverManager.getConnection(h2Url, "sa", "");
             Statement stmt = conn.createStatement()) {
            stmt.execute("CREATE TABLE IF NOT EXISTS salads (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(255) NOT NULL)");
            stmt.execute("CREATE TABLE IF NOT EXISTS products (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(255), product_type VARCHAR(50), kcal_per_100g DOUBLE, proteins DOUBLE, fats DOUBLE, carbs DOUBLE)");
            stmt.execute("CREATE TABLE IF NOT EXISTS ingredients (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, salad_id BIGINT, product_id BIGINT, weight_grams DOUBLE, processing_state VARCHAR(50), FOREIGN KEY(salad_id) REFERENCES salads(id) ON DELETE CASCADE, FOREIGN KEY(product_id) REFERENCES products(id))");
        } catch (Exception ignored) {}

        mockSaladRepo = Mockito.mock(SaladRepository.class);
        mockMainController = Mockito.mock(MainController.class);

        testSalad = new Salad("Цезар");
        testSalad.setId(101L);

        Product chicken = new RootVegetable(1L, "Курка", 120.0, 20.0, 4.0, 0.0, 0.0);
        Product saladLeaves = new RootVegetable(2L, "Салат", 15.0, 1.0, 0.0, 2.0, 0.0);
        Product carrotWithTip = new RootVegetable(3L, "Морква екстра", 41.0, 1.0, 0.1, 9.5, 12.0);

        testSalad.addIngredient(new Ingredient(chicken, 100.0, ProcessingState.RAW)); // 120 kcal
        testSalad.addIngredient(new Ingredient(saladLeaves, 200.0, ProcessingState.RAW)); // 30 kcal
        testSalad.addIngredient(new Ingredient(carrotWithTip, 100.0, ProcessingState.RAW));

        when(mockSaladRepo.findAll()).thenReturn(List.of(testSalad));

        FXMLLoader loader = new FXMLLoader(Thread.currentThread().getContextClassLoader().getResource("org/lpnu/chef_app/views/recipe-book-view.fxml"));
        Scene scene = new Scene(loader.load());

        controller = loader.getController();
        controller.setSaladRepository(mockSaladRepo);
        controller.setMainController(mockMainController);

        interact(() -> controller.refresh());

        stage.setScene(scene);
        stage.show();
    }

    @Test
    @DisplayName("Список салатів успішно завантажується та форматує текст комірки")
    void testSaladListViewLoadsCorrectly() {
        ListView<Salad> listView = lookup("#saladListView").queryListView();
        assertEquals(1, listView.getItems().size());

        interact(() -> listView.getSelectionModel().select(0));
        WaitForAsyncUtils.waitForFxEvents();

        Label detailsTitle = lookup("#detailsTitleLabel").queryAs(Label.class);
        assertEquals("Рецепт \"Цезар\"", detailsTitle.getText());
    }

    @Test
    @DisplayName("Вибір салату відображає правильні сумарні калорії, макроси та розблоковує експорт")
    void testShowSaladDetails() {
        ListView<Salad> listView = lookup("#saladListView").queryListView();
        interact(() -> listView.getSelectionModel().select(0));
        WaitForAsyncUtils.waitForFxEvents();

        Label lblTotalKcal = lookup("#lblTotalKcal").queryAs(Label.class);
        Label lblMacros = lookup("#lblMacros").queryAs(Label.class);
        Button exportBtn = lookup("#exportButton").queryButton();

        assertTrue(lblTotalKcal.getText().contains("191.0 ккал") || lblTotalKcal.getText().contains("191.0"));
        assertEquals("23.0 / 4.1 / 13.5", lblMacros.getText());
        assertFalse(exportBtn.isDisabled(), "Кнопка експорту має стати активною");
    }

    @Test
    @DisplayName("Пошук відфільтровує салати за назвою")
    void testSaladSearch() {
        ListView<Salad> listView = lookup("#saladListView").queryListView();
        TextField searchField = lookup("#searchSaladField").queryAs(TextField.class);

        assertEquals(1, listView.getItems().size());

        clickOn(searchField).write("Олів'є");
        WaitForAsyncUtils.waitForFxEvents();
        assertEquals(0, listView.getItems().size(), "Салат 'Цезар' має зникнути");

        doubleClickOn(searchField).write("");
        clickOn(searchField).write("Цезар");
        WaitForAsyncUtils.waitForFxEvents();
        assertEquals(1, listView.getItems().size());
    }

    @Test
    @DisplayName("Фільтр калорійності інгредієнтів (handleFilterIngredients) працює коректно")
    void testIngredientKcalFiltering() {
        ListView<Salad> listView = lookup("#saladListView").queryListView();
        interact(() -> listView.getSelectionModel().select(0));
        WaitForAsyncUtils.waitForFxEvents();

        TableView<Ingredient> detailsTable = lookup("#detailsTable").queryTableView();
        assertEquals(3, detailsTable.getItems().size(), "Спочатку відображаються всі три інгредієнти");

        clickOn(controller.minKcalField).write("50");
        clickOn(controller.maxKcalField).write("200");

        interact(() -> controller.handleFilterIngredients());
        WaitForAsyncUtils.waitForFxEvents();

        assertEquals(1, detailsTable.getItems().size(), "Після фільтрації має залишитися 1 інгредієнт");
        assertEquals("Курка", detailsTable.getItems().get(0).getProduct().getName());

        // Resetting filter
        interact(() -> controller.handleResetFilter());
        WaitForAsyncUtils.waitForFxEvents();
        assertEquals(3, detailsTable.getItems().size(), "Після скидання знову має бути 3 елементи");
    }

    @Test
    @DisplayName("Сортування інгредієнтів у таблиці через ComboBox змінює порядок")
    void testSortingIngredients() {
        ListView<Salad> listView = lookup("#saladListView").queryListView();
        interact(() -> listView.getSelectionModel().select(0));
        WaitForAsyncUtils.waitForFxEvents();

        ComboBox<String> sortBox = lookup("#sortComboBox").queryComboBox();
        TableView<Ingredient> detailsTable = lookup("#detailsTable").queryTableView();

        // Калорійність ↑
        interact(() -> sortBox.getSelectionModel().select("Калорійністю ↑"));
        WaitForAsyncUtils.waitForFxEvents();
        assertEquals("Курка", detailsTable.getItems().get(0).getProduct().getName());

        // Калорійність ↓
        interact(() -> sortBox.getSelectionModel().select("Калорійністю ↓"));
        WaitForAsyncUtils.waitForFxEvents();
        assertEquals("Салат", detailsTable.getItems().get(0).getProduct().getName());
    }

    @Test
    @DisplayName("handleEditSalad() успішно перемикає додаток у режим редагування через MainController")
    void testEditSaladNavigation() {
        ListView<Salad> listView = lookup("#saladListView").queryListView();
        interact(() -> listView.getSelectionModel().select(0));
        WaitForAsyncUtils.waitForFxEvents();

        interact(() -> controller.handleEditSalad());
        WaitForAsyncUtils.waitForFxEvents();

        verify(mockMainController, times(1)).switchToEditMode(testSalad);
    }

    @Test
    @DisplayName("handleDeleteSalad() ігнорує виклик, якщо салат не обрано")
    void testDeleteActionWithNoSelection() {
        ListView<Salad> listView = lookup("#saladListView").queryListView();
        interact(() -> listView.getSelectionModel().clearSelection());

        assertDoesNotThrow(() -> interact(() -> controller.handleDeleteSalad()));
        verify(mockSaladRepo, never()).delete(anyLong());
    }

    @Test
    @DisplayName("handleDeleteSalad() ігнорує виклик, якщо жоден салат не обрано")
    void testDeleteSaladNoSelection() {
        interact(() -> lookup("#saladListView").queryListView().getSelectionModel().clearSelection());
        WaitForAsyncUtils.waitForFxEvents();

        assertDoesNotThrow(() -> interact(() -> controller.handleDeleteSalad()));
        verify(mockSaladRepo, never()).delete(anyLong());
    }

    @Test
    @DisplayName("handleDeleteSalad() перериває роботу, якщо у салату відсутній ID")
    void testDeleteSaladMissingId() {
        Salad saladWithoutId = new Salad("Салат без ID");
        saladWithoutId.setId(null);

        when(mockSaladRepo.findAll()).thenReturn(List.of(saladWithoutId));

        interact(() -> {
            controller.loadSalads();
            ListView<Salad> listView = lookup("#saladListView").queryListView();
            listView.getSelectionModel().select(0);
        });
        WaitForAsyncUtils.waitForFxEvents();

        assertDoesNotThrow(() -> interact(() -> controller.handleDeleteSalad()));
        verify(mockSaladRepo, never()).delete(anyLong());

        when(mockSaladRepo.findAll()).thenReturn(List.of(testSalad));
        interact(() -> controller.loadSalads());
        WaitForAsyncUtils.waitForFxEvents();
    }

    @Test
    @DisplayName("handleDeleteSalad() успішно видаляє салат після підтвердження користувачем (ButtonType.OK)")
    void testDeleteSaladConfirmed() {
        Salad deleteSalad = new Salad("Цезар");
        deleteSalad.setId(42L);

        when(mockSaladRepo.findAll()).thenReturn(List.of(deleteSalad));

        interact(() -> {
            controller.loadSalads();
            ListView<Salad> listView = lookup("#saladListView").queryListView();
            listView.getSelectionModel().select(0);
        });
        WaitForAsyncUtils.waitForFxEvents();

        Platform.runLater(() -> controller.handleDeleteSalad());
        WaitForAsyncUtils.waitForFxEvents();

        clickOn("OK");
        WaitForAsyncUtils.waitForFxEvents();

        verify(mockSaladRepo, times(1)).delete(42L);

        Label lblTotalKcal = lookup("#lblTotalKcal").query();
        Label lblMacros = lookup("#lblMacros").query();
        Label detailsTitle = lookup("#detailsTitleLabel").query();
        Button exportBtn = lookup("#exportButton").queryButton();

        assertEquals("0.0", lblTotalKcal.getText());
        assertEquals("0.0 / 0.0 / 0.0", lblMacros.getText());
        assertEquals("Оберіть салат для перегляду", detailsTitle.getText());
        assertTrue(exportBtn.isDisabled());

        when(mockSaladRepo.findAll()).thenReturn(List.of(testSalad));
    }

    @Test
    @DisplayName("handleDeleteSalad() скасовує видалення, якщо користувач натискає Cancel")
    void testDeleteSaladCancelled() {
        Salad cancelSalad = new Salad("Грецький");
        cancelSalad.setId(77L);

        when(mockSaladRepo.findAll()).thenReturn(List.of(cancelSalad));

        interact(() -> {
            controller.loadSalads();
            ListView<Salad> listView = lookup("#saladListView").queryListView();
            listView.getSelectionModel().select(0);
        });
        WaitForAsyncUtils.waitForFxEvents();

        Platform.runLater(() -> controller.handleDeleteSalad());
        WaitForAsyncUtils.waitForFxEvents();

        try {
            clickOn("Скасувати");
        } catch (Exception e) {
            clickOn("Cancel");
        }
        WaitForAsyncUtils.waitForFxEvents();

        verify(mockSaladRepo, never()).delete(77L);
        when(mockSaladRepo.findAll()).thenReturn(List.of(testSalad));
    }

    @Test
    @DisplayName("handleExportToTxt() виводить попередження, якщо не обрано салат для експорту")
    void testExportToTxtNoSelection() {
        interact(() -> lookup("#saladListView").queryListView().getSelectionModel().clearSelection());
        WaitForAsyncUtils.waitForFxEvents();

        Platform.runLater(() -> controller.handleExportToTxt());
        WaitForAsyncUtils.waitForFxEvents();

        clickOn("OK");
    }

    @Test
    @DisplayName("saveToFile() успішно форматує та записує рецепт салату зі специфічними порадами у файл")
    void testSaveToFileSuccessWorkflow() throws java.io.IOException {
        Salad exportSalad = new Salad("Вітамінний");
        exportSalad.setId(10L);

        Product carrot = new RootVegetable(1L, "Морква", 41.0, 1.0, 0.1, 9.5, 12.0);
        Ingredient ing = new Ingredient(carrot, 150.0, ProcessingState.RAW);
        exportSalad.addIngredient(ing);

        java.io.File tempFile = java.io.File.createTempFile("salad_recipe_test", ".txt");
        tempFile.deleteOnExit();

        interact(() -> {
            try {
                java.lang.reflect.Method method = RecipeBookController.class.getDeclaredMethod(
                        "saveToFile", Salad.class, java.io.File.class);
                method.setAccessible(true);

                Platform.runLater(() -> {
                    try {
                        method.invoke(controller, exportSalad, tempFile);
                    } catch (Exception ignored) {}
                });
            } catch (NoSuchMethodException e) {
                fail("Не знайдено метод saveToFile через рефлексію");
            }
        });
        WaitForAsyncUtils.waitForFxEvents();

        clickOn("OK");
        WaitForAsyncUtils.waitForFxEvents();

        String fileContent = java.nio.file.Files.readString(tempFile.toPath());
        assertTrue(fileContent.contains("Рецепт салату: \"Вітамінний\""));
        assertTrue(fileContent.contains("Інгредієнт"));
        assertTrue(fileContent.contains("Морква"));
        assertTrue(fileContent.contains("Загальна енергетична цінність"));
    }

    @Test
    @DisplayName("saveToFile() перехоплює IOException та коректно виводить вікно з помилкою (блок catch)")
    void testSaveToFileThrowsIOException() {
        Salad errorSalad = new Salad("Збійний Експорт");
        java.io.File invalidFile = new java.io.File("");

        try {
            java.lang.reflect.Method method = RecipeBookController.class.getDeclaredMethod(
                    "saveToFile", Salad.class, java.io.File.class);
            method.setAccessible(true);

            Platform.runLater(() -> {
                try {
                    method.invoke(controller, errorSalad, invalidFile);
                } catch (Exception ignored) {}
            });
            WaitForAsyncUtils.waitForFxEvents();

            clickOn("OK");
            WaitForAsyncUtils.waitForFxEvents();

        } catch (NoSuchMethodException e) {
            fail("Не вдалося отримати доступ до saveToFile для тестування IOException");
        }
    }

    @Test
    @DisplayName("Вибір інгредієнта в таблиці деталей відображає його кулінарну пораду в tipTextArea")
    void testIngredientSelectionShowsCookingTip() {
        // Selecting salad, so table takes ingredients from the mock
        ListView<Salad> listView = lookup("#saladListView").queryListView();
        interact(() -> listView.getSelectionModel().select(0));
        WaitForAsyncUtils.waitForFxEvents();

        TableView<Ingredient> detailsTable = lookup("#detailsTable").queryTableView();
        TextArea tipTextArea = lookup("#tipTextArea").queryAs(TextArea.class);

        // No preparation tip
        interact(() -> detailsTable.getSelectionModel().select(0));
        WaitForAsyncUtils.waitForFxEvents();

        assertEquals("Курка: поради немає.", tipTextArea.getText());

        // Present preparation tip
        interact(() -> detailsTable.getSelectionModel().select(2));
        WaitForAsyncUtils.waitForFxEvents();

        assertTrue(tipTextArea.getText().startsWith("Морква екстра:"));
        assertFalse(tipTextArea.getText().contains("поради немає."));
    }

    @Test
    @DisplayName("Скидання виділення інгредієнта (newVal == null) повністю очищує текстове поле порад")
    void testIngredientSelectionResetClearsTipTextArea() {
        // Selecting salad and ingredient, so preparation tip loads
        ListView<Salad> listView = lookup("#saladListView").queryListView();
        interact(() -> listView.getSelectionModel().select(0));
        WaitForAsyncUtils.waitForFxEvents();

        TableView<Ingredient> detailsTable = lookup("#detailsTable").queryTableView();
        TextArea tipTextArea = lookup("#tipTextArea").queryAs(TextArea.class);

        interact(() -> detailsTable.getSelectionModel().select(0));
        WaitForAsyncUtils.waitForFxEvents();
        assertFalse(tipTextArea.getText().isEmpty(), "Текстова область спочатку повинна містити текст");

        // Clearing selection
        interact(() -> detailsTable.getSelectionModel().clearSelection());
        WaitForAsyncUtils.waitForFxEvents();

        // Preparation tip form must be empty
        assertTrue(tipTextArea.getText().isEmpty(), "Після скасування виділення поле порад має очиститися");
    }

}