package org.lpnu.chef_app.repository;

import org.junit.jupiter.api.*;
import org.lpnu.chef_app.model.*;
import org.lpnu.chef_app.model.enums.Allergen;
import org.lpnu.chef_app.model.enums.ProductType;
import java.sql.*;
import java.util.List;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;

class JdbcProductRepositoryTest {
    private static final String H2_URL = "jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL";
    private JdbcProductRepository repository;

    @BeforeAll
    static void setupAll() {
        System.setProperty("test.db.url", H2_URL);
    }

    @AfterAll
    static void tearDownAll() {
        System.clearProperty("test.db.url");
    }

    @BeforeEach
    void setUp() throws SQLException {
        try (Connection conn = DriverManager.getConnection(H2_URL, "sa", "");
             Statement stmt = conn.createStatement()) {

            stmt.execute("DROP ALL OBJECTS");

            stmt.execute("CREATE TABLE products (" +
                    "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "name VARCHAR(255) NOT NULL, " +
                    "kcal_per_100g DOUBLE, " +
                    "proteins DOUBLE, " +
                    "fats DOUBLE, " +
                    "carbs DOUBLE, " +
                    "product_type VARCHAR(50))");

            stmt.execute("CREATE TABLE root_vegetables (product_id BIGINT PRIMARY KEY, sugar_content DOUBLE, FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE)");
            stmt.execute("CREATE TABLE tuber_vegetables (product_id BIGINT PRIMARY KEY, starch_content DOUBLE, FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE)");
            stmt.execute("CREATE TABLE fruiting_vegetables (product_id BIGINT PRIMARY KEY, water_content_percent DOUBLE, FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE)");
            stmt.execute("CREATE TABLE leafy_vegetables (product_id BIGINT PRIMARY KEY, fiber_content DOUBLE, FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE)");
            stmt.execute("CREATE TABLE dressings (product_id BIGINT PRIMARY KEY, is_fat_based BOOLEAN, FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE)");
            stmt.execute("CREATE TABLE toppings (product_id BIGINT PRIMARY KEY, allergen VARCHAR(50), is_crunchy BOOLEAN, FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE)");
        }
        repository = new JdbcProductRepository();
    }

    @Test
    @DisplayName("Покриття всіх типів продуктів: Tuber, Fruiting, Leafy, Topping")
    void testSaveAndFindVariousProducts() {
        // 1. Tuber
        TuberVegetable potato = new TuberVegetable(null, "Картопля", 77, 2, 0.4, 16, 15.0);
        repository.save(potato);

        // 2. Topping with allergen
        Topping nuts = new Topping(null, "Горіхи", 600, 15, 50, 10, Allergen.NUTS, true);
        repository.save(nuts);
        Long nutsId = nuts.getID(); // Динамічно беремо реальний ID для перевірки

        // 3. Leafy
        LeafyVegetable spinach = new LeafyVegetable(null, "Шпинат", 23, 2.9, 0.4, 3.6, 2.2);
        repository.save(spinach);

        List<Product> all = repository.findAll();
        assertEquals(3, all.size());

        Optional<Product> foundNuts = repository.findById(nutsId);
        assertTrue(foundNuts.isPresent());
        assertEquals(Allergen.NUTS, ((Topping) foundNuts.get()).getAllergen());
        assertTrue(((Topping) foundNuts.get()).getIsCrunchy());
    }

    @Test
    @DisplayName("update() успішно змінює дані продукту")
    void testUpdateProduct() {
        RootVegetable carrot = new RootVegetable(null, "Морква", 41, 1, 0, 9, 5.0);
        repository.save(carrot);

        Long realId = carrot.getID();
        assertNotNull(realId, "База даних мала згенерувати ID для продукту");

        RootVegetable updatedCarrot = new RootVegetable(realId, "Морква Екстра", 45, 1.2, 0.1, 10, 6.5);
        repository.update(updatedCarrot);

        Optional<Product> found = repository.findById(realId);

        assertTrue(found.isPresent(), "Продукт повинен існувати в базі");
        assertEquals("Морква Екстра", found.get().getName());
        assertEquals(6.5, ((RootVegetable) found.get()).getSugarContent(), "Цукор мав оновитися до 6.5");
    }

    @Test
    @DisplayName("findById() повертає Optional.empty для неіснуючого ID")
    void testFindByIdNotFound() {
        Optional<Product> found = repository.findById(999L);
        assertFalse(found.isPresent());
    }

    @Test
    @DisplayName("Покриття Dressing та FruitingVegetable")
    void testDressingAndFruiting() {
        Dressing oil = new Dressing(null, "Олія", 800, 0, 99, 0, true);
        FruitingVegetable tomato = new FruitingVegetable(null, "Томат", 20, 1, 0, 4, 94.0);

        repository.save(oil);
        repository.save(tomato);

        Long oilId = oil.getID();
        Long tomatoId = tomato.getID();

        Product foundOil = repository.findById(oilId).get();
        assertTrue(((Dressing) foundOil).getIsFatBased());
        assertEquals(ProductType.DRESSING, foundOil.getType());

        Product foundTomato = repository.findById(tomatoId).get();
        assertEquals(94.0, ((FruitingVegetable) foundTomato).getWaterContentPercent());
    }

    @Test
    @DisplayName("delete() видаляє основний продукт та дані з дочірніх таблиць")
    void testDeleteFullCycle() throws SQLException {
        // Saving a product
        RootVegetable carrot = new RootVegetable(null, "Морква", 41.0, 1.3, 0.1, 9.3, 5.0);
        repository.save(carrot);

        Long carrotId = carrot.getID(); // Отримуємо динамічний ID

        // Checking if it is present in daughter table
        try (Connection conn = DriverManager.getConnection(H2_URL, "sa", "");
             PreparedStatement stmt = conn.prepareStatement("SELECT COUNT(*) FROM root_vegetables WHERE product_id = ?")) {
            stmt.setLong(1, carrotId);
            try (ResultSet rs = stmt.executeQuery()) {
                rs.next();
                assertEquals(1, rs.getInt(1), "Запис у root_vegetables має існувати перед видаленням");
            }
        }

        // Deleting using real generated ID
        repository.delete(carrotId);

        // Checking if both tables are empty
        Optional<Product> found = repository.findById(carrotId);
        assertFalse(found.isPresent());

        try (Connection conn = DriverManager.getConnection(H2_URL, "sa", "");
             PreparedStatement stmt = conn.prepareStatement("SELECT COUNT(*) FROM root_vegetables WHERE product_id = ?")) {
            stmt.setLong(1, carrotId);
            try (ResultSet rs = stmt.executeQuery()) {
                rs.next();
                assertEquals(0, rs.getInt(1), "Запис у root_vegetables має бути видалений автоматично (CASCADE)");
            }
        }
    }

    @Test
    @DisplayName("updateSpecificData() покриття: оновлення всіх типів продуктів")
    void testUpdateSpecificDataAllTypes() {
        List<Product> products = List.of(
                new TuberVegetable(null, "Old Tuber", 10, 1, 1, 1, 10.0),
                new FruitingVegetable(null, "Old Fruit", 10, 1, 1, 1, 80.0),
                new LeafyVegetable(null, "Old Leaf", 10, 1, 1, 1, 2.0),
                new Dressing(null, "Old Dressing", 10, 1, 1, 1, false),
                new Topping(null, "Old Topping", 10, 1, 1, 1, Allergen.NONE, false)
        );

        for (Product p : products) {
            repository.save(p);
        }

        Long tuberId = products.get(0).getID();
        Long fruitId = products.get(1).getID();
        Long leafId = products.get(2).getID();
        Long dressingId = products.get(3).getID();
        Long toppingId = products.get(4).getID();

        assertNotNull(tuberId);
        assertNotNull(fruitId);
        assertNotNull(leafId);
        assertNotNull(dressingId);
        assertNotNull(toppingId);

        List<Product> updatedProducts = List.of(
                new TuberVegetable(tuberId, "New Tuber", 15, 2, 2, 2, 25.0),
                new FruitingVegetable(fruitId, "New Fruit", 15, 2, 2, 2, 95.0),
                new LeafyVegetable(leafId, "New Leaf", 15, 2, 2, 2, 5.0),
                new Dressing(dressingId, "New Dressing", 15, 2, 2, 2, true),
                new Topping(toppingId, "New Topping", 15, 2, 2, 2, Allergen.EGGS, true)
        );

        for (Product p : updatedProducts) {
            assertDoesNotThrow(() -> repository.update(p), "Update failed for " + p.getClass().getSimpleName());
        }

        List<Product> finalProducts = repository.findAll();
        assertFalse(finalProducts.isEmpty());

        assertEquals(25.0, ((TuberVegetable) repository.findById(tuberId).orElseThrow()).getStarchContent());
        assertEquals(95.0, ((FruitingVegetable) repository.findById(fruitId).orElseThrow()).getWaterContentPercent());
        assertEquals(5.0, ((LeafyVegetable) repository.findById(leafId).orElseThrow()).getFiberContent());
        assertTrue(((Dressing) repository.findById(dressingId).orElseThrow()).getIsFatBased());
        assertEquals(Allergen.EGGS, ((Topping) repository.findById(toppingId).orElseThrow()).getAllergen());
        assertTrue(((Topping) repository.findById(toppingId).orElseThrow()).getIsCrunchy());
    }

    @Test
    @DisplayName("findAll() перехоплює SQLException і повертає RuntimeException (блок catch)")
    void testFindAllThrowsRuntimeExceptionOnDatabaseError() throws SQLException {
        try (Connection conn = DriverManager.getConnection(H2_URL, "sa", "");
             Statement stmt = conn.createStatement()) {
            stmt.execute("DROP TABLE products CASCADE");
        }

        RuntimeException exception = assertThrows(RuntimeException.class, () -> repository.findAll());
        assertTrue(exception.getMessage().contains("Не вдалося отримати дані з бази"));
        assertNotNull(exception.getCause(), "Оригінальний SQLException має бути збережений як Cause");
    }

    @Test
    @DisplayName("findById() перехоплює SQLException і повертає RuntimeException (блок catch)")
    void testFindByIdThrowsRuntimeExceptionOnDatabaseError() throws SQLException {
        try (Connection conn = DriverManager.getConnection(H2_URL, "sa", "");
             Statement stmt = conn.createStatement()) {
            stmt.execute("DROP TABLE products CASCADE");
        }

        RuntimeException exception = assertThrows(RuntimeException.class, () -> repository.findById(1L));
        assertTrue(exception.getMessage().contains("Не вдалося отримати дані з бази"));
    }

    @Test
    @DisplayName("save() успішно виконує conn.rollback() при помилці всередині транзакції (блок catch SQLExpcetion)")
    void testSaveRollbacksTransactionOnSQLException() {
        RootVegetable standardCarrot = new RootVegetable(null, "Звичайна морква", 40.0, 1.0, 0.0, 9.0, 5.0);
        repository.save(standardCarrot);

        Long standardId = standardCarrot.getID();
        RootVegetable brokenCarrot = new RootVegetable(standardId, "Збійна транзакція", 50.0, 1.0, 0.0, 10.0, 4.0);

        try (Connection conn = DriverManager.getConnection(H2_URL, "sa", "");
             Statement stmt = conn.createStatement()) {
            stmt.execute("DROP TABLE root_vegetables CASCADE");
        } catch (SQLException ignored) {}

        RuntimeException exception = assertThrows(RuntimeException.class, () -> repository.save(brokenCarrot));
        assertTrue(exception.getMessage().contains("Транзакція провалилась") || exception.getMessage().contains("Помилка при збереженні продукту"));
    }

    @Test
    @DisplayName("save() перехоплює збій з'єднання на самому початку транзакції")
    void testSaveCatchesConnectionFailure() throws SQLException {
        Product testProduct = new RootVegetable(null, "Морква Нова", 40.0, 1.0, 0.0, 9.0, 5.0);

        try (Connection conn = DriverManager.getConnection(H2_URL, "sa", "");
             Statement stmt = conn.createStatement()) {
            stmt.execute("DROP TABLE products CASCADE");
        }

        RuntimeException exception = assertThrows(RuntimeException.class, () -> repository.save(testProduct));
        assertTrue(exception.getMessage().contains("Помилка при збереженні продукту") || exception.getMessage().contains("Транзакція провалилась"));
    }
}