package org.lpnu.chef_app.repository;

import org.junit.jupiter.api.*;
import org.lpnu.chef_app.model.*;
import org.lpnu.chef_app.model.enums.ProcessingState;
import org.lpnu.chef_app.util.DatabaseConnector;

import java.sql.*;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class JdbcSaladRepositoryTest {
    private static final String H2_URL = "jdbc:h2:mem:salad_db;DB_CLOSE_DELAY=-1;MODE=PostgreSQL";
    private JdbcSaladRepository saladRepository;
    private JdbcProductRepository productRepository;

    @BeforeAll
    static void setupAll() {
        System.setProperty("test.db.url", H2_URL);
    }

    @BeforeEach
    void setUp() throws SQLException {
        try (Connection conn = DriverManager.getConnection(H2_URL, "sa", "");
             Statement stmt = conn.createStatement()) {

            stmt.execute("DROP ALL OBJECTS");

            stmt.execute("CREATE TABLE products (" +
                    "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "name VARCHAR(255), " +
                    "product_type VARCHAR(50), " +
                    "kcal_per_100g DOUBLE, " +
                    "proteins DOUBLE, " +
                    "fats DOUBLE, " +
                    "carbs DOUBLE)");

            stmt.execute("CREATE TABLE root_vegetables (product_id BIGINT PRIMARY KEY, sugar_content DOUBLE, FOREIGN KEY(product_id) REFERENCES products(id))");
            stmt.execute("CREATE TABLE tuber_vegetables (product_id BIGINT PRIMARY KEY, starch_content DOUBLE, FOREIGN KEY(product_id) REFERENCES products(id))");
            stmt.execute("CREATE TABLE fruiting_vegetables (product_id BIGINT PRIMARY KEY, water_content_percent DOUBLE, FOREIGN KEY(product_id) REFERENCES products(id))");
            stmt.execute("CREATE TABLE leafy_vegetables (product_id BIGINT PRIMARY KEY, fiber_content DOUBLE, FOREIGN KEY(product_id) REFERENCES products(id))");
            stmt.execute("CREATE TABLE dressings (product_id BIGINT PRIMARY KEY, is_fat_based BOOLEAN, FOREIGN KEY(product_id) REFERENCES products(id))");
            stmt.execute("CREATE TABLE toppings (product_id BIGINT PRIMARY KEY, allergen VARCHAR(50), is_crunchy BOOLEAN, FOREIGN KEY(product_id) REFERENCES products(id))");

            stmt.execute("CREATE TABLE salads (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(255) NOT NULL)");
            stmt.execute("CREATE TABLE ingredients (" +
                    "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "salad_id BIGINT, " +
                    "product_id BIGINT, " +
                    "weight_grams DOUBLE, " +
                    "processing_state VARCHAR(50), " +
                    "FOREIGN KEY(salad_id) REFERENCES salads(id) ON DELETE CASCADE, " +
                    "FOREIGN KEY(product_id) REFERENCES products(id))");
        }
        saladRepository = new JdbcSaladRepository();
        productRepository = new JdbcProductRepository();
    }

    @Test
    @DisplayName("save() та findAll(): збереження салату з інгредієнтами")
    void testSaveAndFindAllSalads() {
        RootVegetable carrot = new RootVegetable(null, "Морква", 41, 0.9, 0.1, 9.6, 5.0);
        productRepository.save(carrot);

        Salad salad = new Salad("Вітамінний");
        salad.addIngredient(new Ingredient(carrot, 200, ProcessingState.RAW));

        assertDoesNotThrow(() -> saladRepository.save(salad));

        List<Salad> foundSalads = saladRepository.findAll();
        assertFalse(foundSalads.isEmpty());
        assertEquals(1, foundSalads.get(0).getIngredients().size());
    }

    @Test
    @DisplayName("update(): зміна назви салату та складу інгредієнтів")
    void testUpdateSalad() {
        // Initial product
        RootVegetable product1 = new RootVegetable(null, "Продукт 1", 10, 1, 1, 1, 1);
        productRepository.save(product1);

        Salad salad = new Salad("Старий Салат");
        salad.addIngredient(new Ingredient(product1, 100, ProcessingState.RAW));
        saladRepository.save(salad); // ID: 1

        // Updating salad
        Salad updatedSalad = new Salad("Новий Салат");

        // Creating another product
        RootVegetable product2 = new RootVegetable(null, "Продукт 2", 20, 2, 2, 2, 2);
        productRepository.save(product2);

        // Adding product2 to salad (product ID is not null now)
        updatedSalad.addIngredient(new Ingredient(product2, 300, ProcessingState.BOILED));
        // Updating salad (ID: 1)
        assertDoesNotThrow(() -> saladRepository.update(updatedSalad, 1L));

        List<Salad> results = saladRepository.findAll();
        assertEquals("Новий Салат", results.get(0).getName());
        assertEquals("Продукт 2", results.get(0).getIngredients().get(0).getProduct().getName());
    }

    @Test
    @DisplayName("delete(): повне видалення салату та його інгредієнтів")
    void testDeleteSalad() throws SQLException {
        Salad salad = new Salad("На видалення");
        saladRepository.save(salad);

        saladRepository.delete(1L);

        assertTrue(saladRepository.findAll().isEmpty());

        // Checking if ingredients table cleaned (CASCADE)
        try (Connection conn = DriverManager.getConnection(H2_URL, "sa", "");
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery("SELECT COUNT(*) FROM ingredients")) {
            rs.next();
            assertEquals(0, rs.getInt(1));
        }
    }

    @Test
    @DisplayName("Покриття ситуації, коли продукт інгредієнта не знайдено")
    void testLoadIngredientsWithMissingProduct() throws SQLException {
        saladRepository.save(new Salad("Порожній салат"));

        try (Connection conn = DriverManager.getConnection(H2_URL, "sa", "");
             Statement stmt = conn.createStatement()) {
            stmt.execute("SET REFERENTIAL_INTEGRITY FALSE");
            stmt.execute("INSERT INTO ingredients (salad_id, product_id, weight_grams, processing_state) VALUES (1, 999, 100, 'RAW')");

            stmt.execute("SET REFERENTIAL_INTEGRITY TRUE");
        }

        Salad salad = saladRepository.findAll().get(0);
        assertTrue(salad.getIngredients().isEmpty(), "Інгредієнт без продукту не повинен завантажуватися");
    }

    @Test
    @DisplayName("save() перехоплює SQLException, робить rollback() та закриває з'єднання в finally (блок catch/finally)")
    void testSaveSaladThrowsSQLExceptionAndRollbacks() throws SQLException {
        Salad badSalad = new Salad("Збійний Салат");
        Product dummyProduct = new RootVegetable(1L, "Морква", 40.0, 1.0, 0.0, 9.0, 5.0);
        badSalad.addIngredient(new Ingredient(dummyProduct, 100, ProcessingState.RAW));

        try {
            // Deleting ingredients table
            try (Connection conn = DriverManager.getConnection(H2_URL, "sa", "");
                 Statement stmt = conn.createStatement()) {
                stmt.execute("DROP TABLE ingredients CASCADE");
            } catch (SQLException ignored) {}

            // Checking error in RuntimeException
            RuntimeException exception = assertThrows(RuntimeException.class, () -> saladRepository.save(badSalad));
            assertTrue(exception.getMessage().contains("Помилка БД при збереженні салату"));

        } finally {
            // Refresing DB structure
            try (Connection conn = DriverManager.getConnection(H2_URL, "sa", "");
                 Statement stmt = conn.createStatement()) {
                stmt.execute("CREATE TABLE ingredients (" +
                        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                        "salad_id BIGINT, " +
                        "product_id BIGINT, " +
                        "weight_grams DOUBLE, " +
                        "processing_state VARCHAR(50), " +
                        "FOREIGN KEY(salad_id) REFERENCES salads(id) ON DELETE CASCADE, " +
                        "FOREIGN KEY(product_id) REFERENCES products(id))");
            } catch (SQLException ignored) {}
        }
    }

    @Test
    @DisplayName("update() перехоплює SQLException, робить rollback() та коректно обробляє збій у finally")
    void testUpdateSaladThrowsSQLExceptionAndRollbacks() throws SQLException {
        Salad saladToUpdate = new Salad("Салат для оновлення");
        saladToUpdate.setId(1L);

        try {
            // Deleting salads table
            try (Connection conn = DriverManager.getConnection(H2_URL, "sa", "");
                 Statement stmt = conn.createStatement()) {
                stmt.execute("DROP TABLE salads CASCADE");
            } catch (SQLException ignored) {}

            RuntimeException exception = assertThrows(RuntimeException.class, () -> saladRepository.update(saladToUpdate, 1L));
            assertTrue(exception.getMessage().contains("Помилка БД при оновленні салату"));

        } finally {
            // Refresing DB structure
            try (Connection conn = DriverManager.getConnection(H2_URL, "sa", "");
                 Statement stmt = conn.createStatement()) {
                stmt.execute("CREATE TABLE salads (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(255) NOT NULL)");
            } catch (SQLException ignored) {}
        }
    }

    @Test
    @DisplayName("loadIngredientsForSalad() перехоплює SQLException і повертає RuntimeException (блок catch)")
    void testLoadIngredientsThrowsRuntimeExceptionOnDatabaseError() throws SQLException {
        try (Connection conn = DriverManager.getConnection(H2_URL, "sa", "");
             Statement stmt = conn.createStatement()) {
            stmt.execute("INSERT INTO salads (name) VALUES ('Тестовий салат для помилки')");
        }

        try {
            // Deleting child table
            try (Connection conn = DriverManager.getConnection(H2_URL, "sa", "");
                 Statement stmt = conn.createStatement()) {
                stmt.execute("DROP TABLE ingredients CASCADE");
            } catch (SQLException ignored) {}

            RuntimeException exception = assertThrows(RuntimeException.class, () -> saladRepository.findAll());
            assertTrue(exception.getMessage().contains("Помилка завантаження інгредієнтів для салату"));

        } finally {
            // Refreshing child table
            try (Connection conn = DriverManager.getConnection(H2_URL, "sa", "");
                 Statement stmt = conn.createStatement()) {
                stmt.execute("CREATE TABLE ingredients (" +
                        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                        "salad_id BIGINT, " +
                        "product_id BIGINT, " +
                        "weight_grams DOUBLE, " +
                        "processing_state VARCHAR(50), " +
                        "FOREIGN KEY(salad_id) REFERENCES salads(id) ON DELETE CASCADE, " +
                        "FOREIGN KEY(product_id) REFERENCES products(id))");
            } catch (SQLException ignored) {}
        }
    }

    @Test
    @DisplayName("getConnection() перехоплює SQLException при некоректному URL та прокидає його далі")
    void testGetConnectionThrowsSQLExceptionOnInvalidUrl() {
        String originalUrl = System.getProperty("test.db.url");

        try {
            // Incorrect URL
            System.setProperty("test.db.url", "jdbc:invalid_subprotocol:mem:test_db");

            // Checking if getConnection() intercepts SQLException,
            assertThrows(java.sql.SQLException.class, () -> {
                DatabaseConnector.getConnection();
            }, "Метод повинен викинути SQLException при невалідному URL");

        } finally {
            if (originalUrl != null) {
                System.setProperty("test.db.url", originalUrl);
            } else {
                System.clearProperty("test.db.url");
            }
        }
    }

    @Test
    @DisplayName("delete() перехоплює SQLException і повертає RuntimeException (блок catch)")
    void testDeleteSaladThrowsRuntimeExceptionOnDatabaseError() throws SQLException {
        Salad salad = new Salad("Салат для збійного видалення");
        saladRepository.save(salad); // ID = 1

        // DELETE salads initiates SQLException
        try (Connection conn = DriverManager.getConnection(H2_URL, "sa", "");
             Statement stmt = conn.createStatement()) {
            stmt.execute("DROP TABLE salads CASCADE");
        } catch (SQLException ignored) {}

        // Cheking if repository intercepts RuntimeException
        RuntimeException exception = assertThrows(RuntimeException.class, () -> saladRepository.delete(1L));

        assertTrue(exception.getMessage().contains("Не вдалося видалити салат з ID: 1"));
        assertNotNull(exception.getCause(), "Оригінальний SQLException має бути збережений як Cause");
    }

    @Test
    @DisplayName("findAll() перехоплює SQLException при збої головної таблиці і повертає RuntimeException (блок catch)")
    void testFindAllSaladsThrowsRuntimeExceptionOnDatabaseError() throws SQLException {
        // Deleting salads table
        try (Connection conn = DriverManager.getConnection(H2_URL, "sa", "");
             Statement stmt = conn.createStatement()) {
            stmt.execute("DROP TABLE salads CASCADE");
        } catch (SQLException ignored) {}

        // Checking findAll() intercepts error query to 'salads' and throws exception
        RuntimeException exception = assertThrows(RuntimeException.class, () -> saladRepository.findAll());

        assertTrue(exception.getMessage().contains("Не вдалося отримати список салатів"));
        assertNotNull(exception.getCause(), "Оригінальний SQLException має бути збережений як Cause");
    }

}